export const WEB_CLIENT = `
const byId=(id)=>document.getElementById(id);
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"\\u0026","<":"\\u003C",">":"\\u003E",'"':"\\u0022","'":"\\u0027"})[char]);
function toast(message,error){const node=byId("toast");node.textContent=message;node.className="toast show"+(error?" err":"");setTimeout(()=>node.className="toast"+(error?" err":""),2600)}
function busy(button,on,label){if(!button)return;if(on){button.dataset.label=button.textContent;button.textContent=label||"Processing…";button.disabled=true;return}if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}button.disabled=false}
async function json(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||data.detail||("HTTP "+response.status));return data}
function showPage(name){document.querySelectorAll(".page").forEach((node)=>node.classList.toggle("active",node.id==="page-"+name));document.querySelectorAll(".nav button").forEach((node)=>node.classList.toggle("active",node.dataset.page===name));if(name==="sessions")loadSessions();if(name==="dashboard")loadDashboard();if(name==="upstream"){loadUpstream();loadOverrides()}}

async function loadConfig(){const data=await json("/__bili/config");if(data.parseError)toast(String(data.parseError),true);const pj=byId("providers-json");if(pj)pj.value=JSON.stringify(data.providers||{},null,2);const pu=byId("proxy-url");if(pu)pu.value=data.upstreamProxy||"";const cj=byId("compress-json");if(cj)cj.value=data.compress?JSON.stringify(data.compress,null,2):"";document.querySelectorAll('input[name="proxy-mode"]').forEach((input)=>input.checked=input.value===(data.upstreamProxyMode||"direct"));const pt=data.passthrough||{enabled:false};const banner=byId("passthrough-banner");if(banner){if(pt.enabled){banner.hidden=false;const ps=byId("passthrough-source");if(ps)ps.textContent=pt.source==="env"?"Environment variable ACP_PASSTHROUGH (or --passthrough flag)":"Config file passthrough: true";const btn=byId("clear-passthrough");if(btn){btn.disabled=pt.source==="env";btn.title=pt.source==="env"?"Must unset ACP_PASSTHROUGH and restart first":""}}else{banner.hidden=true}}return data}
async function loadUpstream(){try{const data=await json("/__bili/upstream");const labels={"provider":"Provider proxy","provider-direct":"Provider direct","bili-env":"BILI_UPSTREAM_PROXY","web-manual":"Web manual proxy","config":"Config file proxy","HTTPS_PROXY":"HTTPS_PROXY","HTTP_PROXY":"HTTP_PROXY","ALL_PROXY":"ALL_PROXY","windows-system":"Windows system proxy","windows-bypass":"Windows bypass list","no-proxy":"NO_PROXY","direct":"Direct"};const src=byId("upstream-source");if(src)src.textContent=labels[data.source]||data.source||"Direct";const eff=byId("upstream-effective");if(eff)eff.textContent=data.proxy||"direct";const pac=byId("upstream-pac");if(pac)pac.textContent=data.autoConfigUrl||"\\u2014";const state=byId("upstream-state");if(state){state.className="status "+(data.connected===true?"ok":data.connected===false?"err":"");state.textContent=data.connected===true?"CONNECT OK":data.connected===false?(data.error||"Connection failed"):"No upstream connection observed yet"}}catch(error){const state=byId("upstream-state");if(state)state.textContent=String(error)}}
async function saveUpstream(){const button=byId("save-upstream");busy(button,true,"Saving…");const mode=document.querySelector('input[name="proxy-mode"]:checked').value;try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({upstreamProxyMode:mode,upstreamProxy:byId("proxy-url").value.trim()||null})});toast("Upstream settings hot-updated");await loadUpstream()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function testUpstream(){const button=byId("test-upstream");busy(button,true,"Testing…");try{const data=await json("/__bili/upstream/test",{method:"POST"});toast("Connection successful, HTTP "+data.status);await loadUpstream()}catch(error){toast(String(error),true);await loadUpstream()}finally{busy(button,false)}}
async function saveProviders(){const button=byId("save-providers");busy(button,true,"Saving…");try{const providers=JSON.parse(byId("providers-json").value);await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("Provider config hot-updated")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function saveCompress(){const button=byId("save-compress");busy(button,true,"Saving…");try{const text=byId("compress-json").value.trim();const compress=text?JSON.parse(text):null;await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({compress})});toast("Compression params hot-updated")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadOverrides(){try{const data=await loadConfig();const providers=data.providers||{};const box=byId("upstream-overrides");if(!box)return;const entries=Object.entries(providers);if(entries.length===0){box.innerHTML='<p class="status">No providers. Add providers in Settings to configure per-URL proxy.</p>';return}box.innerHTML='<table><thead><tr><th>Provider URL</th><th>Upstream proxy (empty=inherit global)</th></tr></thead><tbody>'+entries.map(([url,route])=>'<tr><td class="mono">'+escapeHtml(url)+'</td><td><input class="mono override-proxy" data-url="'+escapeHtml(url)+'" value="'+escapeHtml((route&&route.proxy)||"")+'" placeholder="Inherit global"></td></tr>').join("")+'</tbody></table>'}catch(error){const box=byId("upstream-overrides");if(box)box.textContent=String(error)}}
async function saveOverrides(){const button=byId("save-overrides");busy(button,true,"Saving…");try{const data=await loadConfig();const providers=data.providers||{};document.querySelectorAll(".override-proxy").forEach((input)=>{const url=input.dataset.url;if(!url)return;if(!providers[url])providers[url]={};const val=input.value.trim();if(val)providers[url].proxy=val;else delete providers[url].proxy});await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("Per-URL overrides hot-updated");await loadOverrides()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadSessions(){try{const data=await json("/__bili/stats");const rows=(data.sessions||[]).map((item)=>"<tr><td>"+escapeHtml(item.title||"\\u2014")+"</td><td>"+escapeHtml(item.protocol||"\\u2014")+"</td><td class=mono>"+escapeHtml(item.label||"\\u2014")+"</td><td>"+escapeHtml(item.requests)+"</td><td>"+escapeHtml(item.contextTokens)+"</td><td>"+escapeHtml(new Date(item.lastSeen).toLocaleString())+(item.restored?" <span class=muted>(restored, inactive since boot)</span>":"")+"</td></tr>").join("");byId("sessions-body").innerHTML=rows||'<tr><td colspan="6">No sessions</td></tr>'}catch(error){toast(String(error),true);throw error}}

async function loadDashboard(){try{const data=await json("/__bili/api/stats");byId("stat-sessions").textContent=data.totalSessions;byId("stat-cache-hit").textContent=(data.overallCacheHitRate*100).toFixed(1)+"%";byId("stat-compress-ratio").textContent=(data.overallCompressionRatio*100).toFixed(1)+"%";byId("stat-tokens-saved").textContent=data.tokensSaved.toLocaleString();byId("stat-cost-savings").textContent="$"+data.estimatedCostSavingsUSD.toFixed(2);byId("stat-latency").textContent=data.avgLatencyMs+"ms";renderActivityChart(data.history||[])}catch(e){toast("Dashboard load failed: "+e,true)}}
function renderActivityChart(history){const canvas=byId("activity-chart");if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;const w=canvas.width=canvas.clientWidth;const h=canvas.height;ctx.clearRect(0,0,w,h);if(history.length===0){ctx.fillStyle="#4b5668";ctx.font="12px monospace";ctx.textAlign="center";ctx.fillText("No historical data yet",w/2,h/2);return}const maxTokens=Math.max(...history.map(b=>b.tokens));const padding=40;const chartW=w-padding*2;const chartH=h-padding*2;ctx.strokeStyle="#2b313d";ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=padding+chartH*i/4;ctx.beginPath();ctx.moveTo(padding,y);ctx.lineTo(w-padding,y);ctx.stroke();ctx.fillStyle="#8f98a8";ctx.font="10px monospace";ctx.textAlign="right";ctx.fillText((maxTokens*(1-i/4)/1e6).toFixed(1)+"M",padding-8,y+3)}ctx.beginPath();ctx.strokeStyle="#6ea8fe";ctx.lineWidth=2;history.forEach((b,i)=>{const x=padding+(i/(history.length-1))*chartW;const y=padding+chartH*(1-(b.tokens/maxTokens||0));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.fillStyle="#6ea8fe";history.forEach((b,i)=>{const x=padding+(i/(history.length-1))*chartW;const y=padding+chartH*(1-(b.tokens/maxTokens||0));ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})}
async function refreshSessions(){const button=byId("refresh-sessions");busy(button,true,"Refreshing…");try{await loadSessions();toast("Sessions refreshed")}catch{}finally{busy(button,false)}}

function init(){
document.querySelectorAll(".nav button").forEach((button)=>button.addEventListener("click",()=>showPage(button.dataset.page)));
document.querySelectorAll(".copy-btn").forEach((btn)=>btn.addEventListener("click",async()=>{busy(btn,true,"Copying…");try{await navigator.clipboard.writeText(btn.dataset.copy||"");toast("Copied")}catch(e){toast(String(e),true)}finally{busy(btn,false)}}));
const cpBtn=byId("clear-passthrough");if(cpBtn)cpBtn.addEventListener("click",clearPassthrough);
const suBtn=byId("save-upstream");if(suBtn)suBtn.addEventListener("click",saveUpstream);
const tuBtn=byId("test-upstream");if(tuBtn)tuBtn.addEventListener("click",testUpstream);
const spBtn=byId("save-providers");if(spBtn)spBtn.addEventListener("click",saveProviders);
const scBtn=byId("save-compress");if(scBtn)scBtn.addEventListener("click",saveCompress);
const soBtn=byId("save-overrides");if(soBtn)soBtn.addEventListener("click",saveOverrides);
const rsBtn=byId("refresh-sessions");if(rsBtn)rsBtn.addEventListener("click",refreshSessions);
Promise.all([loadConfig(),loadUpstream(),loadDashboard(),loadSessions()]).catch((error)=>toast(String(error),true));

function isVisible(){return document.visibilityState==="visible"}

function startPolling(){
    setInterval(()=>{
        if(!isVisible())return;
        if(byId("page-sessions").classList.contains("active"))loadSessions().catch(()=>{});
        if(byId("page-dashboard").classList.contains("active"))loadDashboard().catch(()=>{});
    },5000);
}

document.addEventListener("visibilitychange",()=>{
    if(isVisible()){
        if(byId("page-sessions").classList.contains("active"))loadSessions().catch(()=>{});
        if(byId("page-dashboard").classList.contains("active"))loadDashboard().catch(()=>{});
    }
});

startPolling();
}

async function clearPassthrough(){const button=byId("clear-passthrough");busy(button,true,"Processing…");try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({passthrough:null})});toast("Compression restored");await loadConfig()}catch(error){toast(String(error),true)}finally{busy(button,false)}}

if(document.readyState!=="loading"){init()}else{document.addEventListener("DOMContentLoaded",init)}
`;